FROM oven/bun:1.2.19-alpine

RUN apk add --no-cache curl

WORKDIR /app

COPY package.json bun.lockb* ./

RUN bun install

RUN mkdir -p /app/data && chmod 777 /app/data

ENV APP_ENV=development
ENV APP_PORT=80
ENV APP_DATABASE_PATH=/app/data/calendars.db
ENV APP_PASSWORD=password

EXPOSE 80

CMD ["bun", "run", "--watch", "src/index.ts"]
