version: '3.8'

services:
  calendar:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: calendar-app
    ports:
      - "80:80"
    volumes:
      - ./src:/app/src:ro
      - ./public:/app/public:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
      - calendar_data:/app/data
    environment:
      - APP_ENV=development
      - APP_PORT=80
      - APP_DATABASE_PATH=/app/data/calendars.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  calendar_data:
    name: calendar_data
