version: '3.8'

services:
  calendar:
    build: .
    container_name: calendar-app
    ports:
      - "80:80"
    volumes:
      - calendar_data:/app/data
    environment:
      - BUN_ENV=production
      - PORT=80
      - DATABASE_PATH=/app/data/calendars.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  calendar_data:
    name: calendar_data