// @ts-nocheck
import { fileURLToPath, URL } from "node:url";

import { defineConfig } from "vite-plus";
import vue from "@vitejs/plugin-vue";
import { config } from "./src/config.js";
import tailwindcss from "@tailwindcss/vite";

const isDev = process.env.NODE_ENV === "development";

export default defineConfig({
    plugins: [vue(), tailwindcss()],
    resolve: {
        alias: {
            "@": fileURLToPath(new URL("./src/vue", import.meta.url)),
        },
    },
    root: "./src/vue",
    publicDir: "./public",
    server: {
        port: config.app.vuePort,
        host: true,
        strictPort: true, // fail if 3000 is taken
        allowedHosts: ["localhost"],
        proxy: {
            "^/api/(?!.*\\.js$).*": {
                target: `http://localhost:${config.app.port}`,
                changeOrigin: true,
                rewrite: (path) => path.replace(/^\/api/, "/api"),
            },
            "/healthz": {
                target: `http://localhost:${config.app.port}`,
                changeOrigin: true,
                rewrite: (path) => path,
            },
            "/favicon.ico": {
                target: `http://localhost:${config.app.port}`,
                changeOrigin: true,
                rewrite: (path) => path,
            },
        },
    },
    build: {
        outDir: "../../public",
        reportCompressedSize: true,
        chunkSizeWarningLimit: 500,
        emptyOutDir: false,
        rollupOptions: {
            output: {
                entryFileNames: isDev ? `assets/[name].js` : `assets/[name]-[hash].js`,
                chunkFileNames: isDev ? `assets/[name].js` : `assets/[name]-[hash].js`,
                assetFileNames: isDev ? `assets/[name].[ext]` : `assets/[name]-[hash].[ext]`,
                manualChunks(id) {
                    if (id.includes("node_modules/vue/")) return "vendor";
                    if (id.includes("node_modules/@fullcalendar/")) return "fullcalendar";
                },
            },
        },
    },
    test: {
        root: ".",
        env: {
            NODE_ENV: "test",
            APP_ENV: "test",
            APP_PORT: "80",
            APP_VUE_PORT: "3000",
            SESSION_SECRET: "your-session-secret-change-in-production",
        },
        testTimeout: 10000,
        hookTimeout: 10000,
        teardownTimeout: 10000,
    },
    lint: {
        plugins: ["unicorn", "oxc"],
        rules: {
            "constructor-super": "warn",
            "for-direction": "warn",
            "no-async-promise-executor": "warn",
            "no-caller": "warn",
            "no-class-assign": "warn",
            "no-compare-neg-zero": "warn",
            "no-cond-assign": "warn",
            "no-const-assign": "warn",
            "no-constant-binary-expression": "warn",
            "no-constant-condition": "warn",
            "no-control-regex": "warn",
            "no-debugger": "warn",
            "no-delete-var": "warn",
            "no-dupe-class-members": "warn",
            "no-dupe-else-if": "warn",
            "no-dupe-keys": "warn",
            "no-duplicate-case": "warn",
            "no-empty-character-class": "warn",
            "no-empty-pattern": "warn",
            "no-empty-static-block": "warn",
            "no-eval": "warn",
            "no-ex-assign": "warn",
            "no-extra-boolean-cast": "warn",
            "no-func-assign": "warn",
            "no-global-assign": "warn",
            "no-import-assign": "warn",
            "no-invalid-regexp": "warn",
            "no-irregular-whitespace": "warn",
            "no-loss-of-precision": "warn",
            "no-new-native-nonconstructor": "warn",
            "no-nonoctal-decimal-escape": "warn",
            "no-obj-calls": "warn",
            "no-self-assign": "warn",
            "no-setter-return": "warn",
            "no-shadow-restricted-names": "warn",
            "no-sparse-arrays": "warn",
            "no-this-before-super": "warn",
            "no-unassigned-vars": "warn",
            "no-unsafe-finally": "warn",
            "no-unsafe-negation": "warn",
            "no-unsafe-optional-chaining": "warn",
            "no-unused-expressions": "warn",
            "no-unused-labels": "warn",
            "no-unused-private-class-members": "warn",
            "no-unused-vars": "warn",
            "no-useless-backreference": "warn",
            "no-useless-catch": "warn",
            "no-useless-escape": "warn",
            "no-useless-rename": "warn",
            "no-with": "warn",
            "require-yield": "warn",
            "use-isnan": "warn",
            "valid-typeof": "warn",
            "oxc/bad-array-method-on-arguments": "warn",
            "oxc/bad-char-at-comparison": "warn",
            "oxc/bad-comparison-sequence": "warn",
            "oxc/bad-min-max-func": "warn",
            "oxc/bad-object-literal-comparison": "warn",
            "oxc/bad-replace-all-arg": "warn",
            "oxc/const-comparisons": "warn",
            "oxc/double-comparisons": "warn",
            "oxc/erasing-op": "warn",
            "oxc/missing-throw": "warn",
            "oxc/number-arg-out-of-range": "warn",
            "oxc/only-used-in-recursion": "warn",
            "oxc/uninvoked-array-callback": "warn",
            "unicorn/no-await-in-promise-methods": "warn",
            "unicorn/no-empty-file": "warn",
            "unicorn/no-invalid-fetch-options": "warn",
            "unicorn/no-invalid-remove-event-listener": "warn",
            "unicorn/no-new-array": "warn",
            "unicorn/no-single-promise-in-promise-methods": "warn",
            "unicorn/no-thenable": "warn",
            "unicorn/no-unnecessary-await": "warn",
            "unicorn/no-useless-fallback-in-spread": "warn",
            "unicorn/no-useless-length-check": "warn",
            "unicorn/no-useless-spread": "warn",
            "unicorn/prefer-set-size": "warn",
            "unicorn/prefer-string-starts-ends-with": "warn",
        },
        settings: {
            vitest: {
                typecheck: false,
            },
        },
        ignorePatterns: [
            "public/**/*",
            "dist/**/*",
            "coverage/**/*",
            "node_modules/**/*",
            "**/db.sqlite*",
            "scripts/**/*",
        ],
    },
    fmt: {
        tabWidth: 4,
        semi: true,
        useTabs: false,
        singleQuote: false,
        trailingComma: "all",
        bracketSpacing: true,
        printWidth: 100,
        ignorePatterns: [
            "node_modules",
            "coverage",
            "dist",
            "public/assets",
            "package-lock.json",
            "db.sqlite",
            "db.sqlite-shm",
            "db.sqlite-wal",
            "*.min.js",
            "*.min.css",
        ],
    },
});
