CREATE TABLE IF NOT EXISTS calendars (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL DEFAULT '',
    url TEXT NOT NULL UNIQUE,
    color TEXT NOT NULL DEFAULT '#3498db',
    hidden INTEGER NOT NULL DEFAULT 0,
    details INTEGER NOT NULL DEFAULT 0,
    data TEXT,
    events TEXT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER IF NOT EXISTS calendars_updated_at
AFTER UPDATE ON calendars
FOR EACH ROW
BEGIN
    UPDATE calendars SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;